### ISSUE TITLE
Application serverley out of date and crashes on startup

### ISSUE THREAD

**Issue by forever-and-a-day** [UltraSabreman/TriTracker#8]
This app targets much older versions of android, uses outdated permission model, and, best of all, crashes on startup. App either needs rewrite or repo should honestly just be archived.

**Comment by UltraSabreman** [comment]
Yeah this is old and super broken (last commit 7 years ago lol), I don't even program anymore really. I'll go ahead an update the readme and then archive it.

I actually had no idea archiving was a thing, so thanks for that heads up.
